version: "3.8"
services:
  app:
    build: .
    ports:
      - 8080:8080
    env_file:
      - db.env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    env_file:
      - db.env