create sequence orders_sequence start 1 increment 1;
create sequence products_sequence start 1 increment 1;

create table order_status_pon (
    order_id int8 not null,
    status varchar(255)
);

create table orders (
    id int8 not null, phone varchar(255),
    user_address varchar(255),
    user_email varchar(255),
    user_name varchar(255),
    user_surname varchar(255),
    user_id int8, primary key (id)
);

create table pdf_file (
    id int8 generated by default as identity,
    file_name varchar(255),
    pdf bytea,
    type varchar(255),
    primary key (id)
);

create table product_type (
    product_id int8 not null,
    type varchar(255)
);

create table products (
    id int8 not null,
    description varchar(255),
    image_url varchar(255),
    name varchar(255),
    number int8,
    price int8,
    order_id int8,
    primary key (id)
);

create table user_role (
    user_id int8 not null,
    roles varchar(255)
);

create table usr (
    id int8 generated by default as identity,
    active boolean not null,
    address varchar(255),
    email varchar(255),
    name varchar(255),
    password varchar(255),
    phone varchar(255),
    real_name varchar(255),
    surname varchar(255),
    primary key (id)
);

alter table if exists order_status_pon add constraint FK5uyhio03opdugg2e4hkqnc5kn foreign key (order_id) references orders;

alter table if exists orders add constraint FK7ncuqw9n77odylknbo8aikc9w foreign key (user_id) references usr;

alter table if exists product_type add constraint FKls3uvvo6ebnhsa9c6gn7ybnkm foreign key (product_id) references products;

alter table if exists products add constraint FKr3aftk48ylvntpui7l04kbcc1 foreign key (order_id) references orders;

alter table if exists user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references usr;
